### PR TITLE
New parameter for use profile on local server.

### PR DESCRIPTION
**Pull request by carlosdelfino**
Just run the profile is activated by compress_html.profile parameter,
   But if enabled compress_html.only_local_profile parameter,
   just run the profile on the server addressed
   by localhost ip or equivalent

### CODE REVIEW

**Comment by jnvsor** [comment]
So now it has some rather complicated (And incorrect if you use custom local domains, protocol relative urls, etc) logic to enable profiling? I don't see the advantage to just using the profile option in the config, especially considering the logic is based on `site.url` which is in the config anyway.

**Comment by carlosdelfino** [comment]
In the case where you apply, you are serving well, have been practical to have this option.

No need to worry about enabling or disabling profile when sending to the production server, as this only serves in a domain on the Internet, when in my test environment, it automatically active because I left only_local_profile = true parameter.

This in my view help does not have to keep changing the setting when shipped to the production environment.

**Comment by jnvsor** [comment]
> This in my view help does not have to keep changing the setting when shipped to the production environment.

But it does. You have to change `site.url` anyway or half the urls on the site will be broken on production. Flipping an extra bool isn't such a big deal

**Comment by jnvsor** [comment]
Questionable usefulness, not passing tests, and lots of extra code. Going to go ahead and close this

**Pull request closed without merging**
