### PR TITLE
Ignore whitespaces

### LINKED ISSUE #57: Configuration option to remove consecutive whitespace without outputting all on one line
I would prefer my outputted source code to be somewhat easy to read. jekyll-compress-html is hard to read on one line, and jekyll itself is hard to read with dozens of lines of whitespace in between lines.

Could you please add a configuration option that would remove empty lines, but not all whitespace?

Something along the lines of:

```javascript
replace(/\n\s+\n/, "\n")
```

### PR DESCRIPTION
**Pull request by penibelst**
This should close #57.

@jnvsor Your PR #58 is a path I don’t want to go because *human readable* is more or less a matter of taste. Other humans will raise new issues to match their readability standards. I think on all the endless discussions about [indent style](https://en.wikipedia.org/wiki/Indent_style).

### CODE REVIEW

**Comment by penibelst** [comment]
The changes work in Jekyll 3 only. Earlier versions throw an exception sometimes:

```
Liquid Exception: undefined method `split' for nil:NilClass in _layouts/compress.html
```

Maybe the next version should require Jekyll 3 or later?

**Comment by jnvsor** [comment]
That would be nice - I can't see any reason for sticking to 2.

That said, I ran into that a few times myself - usually you can get past it with an if check before running a split

**Comment by jnvsor** [comment]
@penibelst I've thrown in an if around the offending code - should pass now. Want me to make a PR on your PR branch or just write a new PR with the whole lot?

**Comment by penibelst** [comment]
@jnvsor Finally I have time to finish it. Thank you.

**Pull request merged**
